CREATE TABLE `event360_calls` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `delacon_call_identification` text,
  `datetime` datetime DEFAULT NULL,
  `incoming_call_number` text,
  `geo_origin` text,
  `number1300` text,
  `transferred_number` text,
  `time` datetime DEFAULT NULL,
  `result` text,
  `dealer_id` text,
  `dealer_name` text,
  `dealer_category` text,
  `duration` text,
  `durationof1300` text,
  `voice_mail_left` text,
  `search_engine` text,
  `type` text,
  `keyword` text,
  `url` text,
  `extra_tracking` text,
  `converted` text,
  `survey_outcome` text,
  `survey_sales_amount` text,
  `recording_url` text,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;