@if(sizeof($quotations))
    <table>
        <tr>
            <th>Project Quote</th>
            <th>Generated By</th>
            <th>Generated On
            <th>Quotation Status</th>
            <th>Nett Total</th>
            <th>Total Taxes</th>
        </tr>
        @foreach($quotations as $quotation)
            <tr>
                <td>{{ $quotation->project_quote }}</td>
                <td>{{ $quotation->quotedBy->getEmployeeFullName() }}</td>
                <td>{{ $quotation->quoted_datetime }}</td>
                <td>{{ $quotation->quotation_status }}</td>
                <td>{{ $quotation->net_total }}</td>
                <td>{{ $quotation->total_taxes }}</td>
            </tr>
        @endforeach
    </table>
@else
    <p>Not Found.</p>
@endif