@extends('layouts.default')

@section('content')

    <div class="row expanded">
        <div class="large-3 columns">
            <div class="panel">
                <div class="panel-content">
                    <div class="row">
                        <div class="large-12 columns">
                            <label for="search_query">
                                Search by Project Quotes:
                                {{ Form::text('search_query', null, array('placeholder' => 'Search by Project Quotes', 'id' => 'search_query')) }}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label for="generated_by_filter">
                                Generated By:
                                {{ HTML::image('assets/img/loading.gif', 'Loading', array('id' => 'loader_generated_by_filter', 'class' => 'float-center', 'style' => 'display:none')) }}
                                <select name="generated_by_filter" id="generated_by_filter">
                                </select>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label for="customer_filter">
                                Customer:
                                {{ HTML::image('assets/img/loading.gif', 'Loading', array('id' => 'loader_customer_filter', 'class' => 'float-center', 'style' => 'display:none')) }}
                                <select name="customer_filter" id="customer_filter">
                                </select>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label for="status_filter">
                                Status:
                                {{Form::select('status_filter',array(''=>'Select') + Quotation::$quotation_status , '',array('id' => 'status_filter'))}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label for="filter_campaign">
                                Campaign:
                                <select name="filter_campaign" id="filter_campaign" multiple>
                                </select>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label for="filter_lead_source">
                                Source:
                                <select name="filter_lead_source" id="filter_lead_source">
                                    <option value="">All</option>
                                    @foreach(Lead::$lead_sources as $key => $value)
                                        <option value="{{ $key }}">{{ $value }}</option>
                                    @endforeach
                                </select>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-6 columns text-right">
                            <input type="button" value="Clear Filters" class="alert button tiny" style="width: 100%;" onclick="clearFilters()">
                        </div>
                        <div class="large-6 columns text-right">
                            <input type="button" class="button tiny success" value="Search" style="margin-top: 0px; width: 100%;" onclick="loadDashboardData()">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="large-9 columns">
            <div class="panel">
                <div class="panel-heading">
                    <div class="row expanded">
                        <div class="large-12 columns">
                            <h1>Quotations</h1>
                        </div>
                    </div>
                </div>

                <div class="panel-content">
                    {{ HTML::image('assets/img/loading.gif', 'Loading', array('id' => 'loader_quotations', 'class' => 'float-center', 'style' => 'display:none')) }}
                    <div id="response_quotations" style="overflow: scroll;">

                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>

        function loadDashboardData() {
            ajaxLoadQuotationsList(1);

        }

        loadDashboardData();

        /*==================== PAGINATION =========================*/

        $(document).on('click', '#pagination_quotations_list a', function (e) {
            e.preventDefault();
            var page = $(this).attr('href').split('page=')[1];
            //location.hash = page;
            ajaxLoadQuotationsList(page);
        });

        function ajaxLoadQuotationsList(page) {

            $('#loader_quotations').show();
            $('#response_quotations').hide();

            var search_query = $("#search_query").val();
            var generated_by_filter = $("#generated_by_filter").val();
            generated_by_filter = generated_by_filter ? generated_by_filter : '';
            var customer_filter = $("#customer_filter").val();
            customer_filter = customer_filter ? customer_filter : '';
            var status_filter = $("#status_filter").val();
            status_filter = status_filter ? status_filter : '';
            var filter_campaign = $("#filter_campaign").val();
            filter_campaign = filter_campaign ? filter_campaign : '';
            var filter_lead_source = $("#filter_lead_source").val();
            filter_lead_source = filter_lead_source ? filter_lead_source : '';
            var dashboard_filter_date_range = $('#dashboard_filter_date_range').val();
            var dashboard_filter_from_date = $('#dashboard_filter_from_date').val();
            var dashboard_filter_to_date = $('#dashboard_filter_to_date').val();


            $.ajax({
                url: '/quotations/ajax/load-quotations-list?' +
                'page=' + page +
                '&search_query=' + encodeURIComponent(search_query) +
                '&generated_by_filter=' + generated_by_filter +
                '&customer_filter=' + customer_filter +
                '&status_filter=' + status_filter +
                '&filter_campaign=' + filter_campaign +
                '&filter_lead_source=' + filter_lead_source +
                '&dashboard_filter_date_range=' + dashboard_filter_date_range +
                '&dashboard_filter_from_date=' + dashboard_filter_from_date +
                '&dashboard_filter_to_date=' + dashboard_filter_to_date

            }).done(function (data) {

                $('#response_quotations').html(data);
                $('#loader_quotations').hide();
                $('#response_quotations').show();
                $(document).foundation();

            });
        }

        getEmployeesList();

        function getEmployeesList() {
            $.ajax({
                url: '/employees/ajax/get-employees-list'
            }).done(function(data){


                $('#generated_by_filter').empty();

                data = $.parseJSON(data);

                $('#generated_by_filter').append("<option value=''>Select one</option>");

                for(var i in data)
                {

                    $('#generated_by_filter').append("<option value='" + data[i].id +"'>" + data[i].full_name + "</option>");

                }

                $('#generated_by_filter').selectize({
                    create: false,
                    sortField: 'text'
                });
            });
        }

        getCustomersList();

        function getCustomersList() {
            $.ajax({
                url: '/customers/ajax/load-customer-list'
            }).done(function(data){

                $('#customer_filter').empty();

                data = $.parseJSON(data);

                $('#customer_filter').append("<option value=''>Select one</option>");

                for(var i in data)
                {
                    $('#customer_filter').append("<option value='" + data[i].id +"'>" + data[i].customer_name + "</option>");
                }

                $('#customer_filter').selectize({
                    create: false,
                    sortField: 'text'
                });
            });
        }

        function closeRevealEditModal(){
            $('[name="reveal_edit_quotation"]').foundation('close');
        }

        function generatePDF(quotation_id){

            $.post("/quotations/generate-pdf",
                    {
                        quotation_id: quotation_id
                    },
                    function (data, status) {

                        window.open(escape(data), "Title", "");

                    });

        }

        function clearFilters(){
            $("#search_query").val('');
            $("#start_date_filter").val('');
            $("#end_date_filter").val('');
            $("#customer_filter").val('');
            $("#filter_lead_source").val('');

            var generated_by_filter = $('#generated_by_filter').selectize();
            var control_generated_by_filter = generated_by_filter[0].selectize;
            control_generated_by_filter.clear();

            var customer_filter = $('#customer_filter').selectize();
            var control_customer_filter = customer_filter[0].selectize;
            control_customer_filter.clear();

            var filter_campaign = $('#filter_campaign').selectize();
            var control_filter_campaign = filter_campaign[0].selectize;
            control_filter_campaign.clear();

        }

        function getCampaignsList() {
            $.ajax({
                url: '/campaigns/ajax/get-campaigns-list'
            }).done(function (data) {
                $('#filter_campaign').empty();
                data = $.parseJSON(data);
                $('#filter_campaign').append("<option value=''>Campaign</option>");

                for (var i in data) {
                    $('#filter_campaign').append("<option value='" + data[i].auto_tagged_campaign + "'>" + data[i].auto_tagged_campaign + "</option>");
                }

                $('#filter_campaign').selectize({
                    create: false,
                    sortField: 'text'
                });
            });
        }

        getCampaignsList();

    </script>

@stop