<table>
    <tbody>
    <tr>
        <th>Unassigned Leads</th>
        <td>{{$leads_data['leads_unassigned_count']}}</td>
    </tr>
    <tr>
        <th>Assigned</th>
        <td>{{$leads_data['leads_assigned_count']}}</td>
    </tr>
    <tr>
        <th>Contacted</th>
        <td>{{$leads_data['leads_contacted_count']}}</td>
    </tr>
    <tr>
        <th>Closed</th>
        <td>{{$leads_data['leads_closed_count']}}</td>
    </tr>
    <tr>
        <th>Junk</th>
        <td>{{$leads_data['leads_junk_count']}}</td>
    </tr>
    </tbody>
</table>